name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: 🐼 Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🔔 Grant execute permission for gradlew
        run: |
          echo 🐛 如果遇到Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
          echo 💊 那么说明是因为gradle目录没同步到github导致的,检查下是否此目录下有文件没上传
          chmod +x ./gradlew
      - name: 💪 publishVcatalogPublicationToJuneLocalRepository
        run: ./gradlew publishVcatalogPublicationToJuneLocalRepository
      - name: 🧐 dependencyInsight
        run: ./gradlew :check:app:dependencyInsight --dependency protobuf-java --configuration debugCompileClasspath
      - name: 🧬
        run: ./gradlew :check:app:assembleDebug
      - run: echo "💡  succeed."

